#!/bin/sh

echo "Installing everything needed for 2019 FRC development for Macbook"

FRC_YEAR="2019"

VSCODE_WGET_LINK="https://go.microsoft.com/fwlink/?LinkID=620882"
VSCODE_WGET_ZIP_FILE="index.html?LinkID=620882"
VSCODE_INSTALL_PATH="$HOME/Applications"

WPILIB_WGET_LINK="https://github.com/wpilibsuite/allwpilib/releases/download/v2019.4.1/WPILib_Mac-2019.4.1.tar.gz"
WPILIB_WGET_ZIP_FILE="WPILib_Mac-2019.4.1.tar.gz"
WPILIB_INSTALL_PATH="$HOME/frc$FRC_YEAR"

NAVX_WGET_LINK="http://www.kauailabs.com/public_files/navx-mxp/navx-mxp-libs.zip"
NAVX_WGET_ZIP_FILE="navx-mxp-libs.zip"
NAVX_INSTALL_PATH="$WPILIB_INSTALL_PATH/NavX"

CTRE_WGET_LINK="http://www.ctr-electronics.com//downloads/lib/CTRE_FRCLibs_NON-WINDOWS_v4.4.1.10.zip"
CTRE_WGET_ZIP_FILE="CTRE_FRCLibs_NON-WINDOWS_v4.4.1.10.zip"
CTRE_INSTALL_PATH="$WPILIB_INSTALL_PATH/CTRE"

JAVA_HOME="$HOME/frc$FRC_YEAR/jdk"

# Install Homebrew (package manager for macs)
echo "=================================================
          Installing Homebrew
==================================================
"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install git and wget using homebrew
echo "=================================================
        Using Homebrew to install git
=================================================
"
brew install git    # Version Control System used in robotics
echo "=================================================
       Using Homebrew to install wget
=================================================
"
brew install wget   # Needed to install online packages

# Generate Matrix of all the variables to use in loop b/c shellscript doesn't support 2D arrays

VARIABLES_ARRAY=($VSCODE_WGET_LINK $VSCODE_WGET_ZIP_FILE $VSCODE_INSTALL_PATH $WPILIB_WGET_LINK $WPILIB_WGET_ZIP_FILE $WPILIB_INSTALL_PATH $NAVX_WGET_LINK $NAVX_WGET_LINK $NAVX_WGET_ZIP_FILE $NAVX_INSTALL_PATH)
# Creates a variable called matrix that stores all the values in VARIABLES_ARRAY
declare -A matrix
num_rows=4    # Number of things to install
num_columns=3 # Number of variables needed per installation
k=0

for((i=1;i<=num_rows;i++))
do
    for((j=1;j<=num_columns;j++))
    do
        matrix[$i,$j]=${VARIABLES_ARRAY[$k]}
        k=$(( $k + 1 ))
    done
done

# Use Matrix generated to install everything
for((i=1;i<=num_rows;i++))
do
    wget -c ${matrix[$i,1]}
    case ${matrix[$i,2]} in
        *.tar.gz)
            tar xvzf ${matrix[$i,2]} -C ${matrix[$i,3]}
            ;;
        *)
            unzip ${matrix[$i,2]} -d ${matrix[$i,3]}
            ;;
    esac
    rm -f ${matrix[$i,2]}
done
# Set JAVA_HOME

echo "export JAVA_HOME=$JAVA_HOME" >> $HOME/.profile
echo "export PATH=\"$PATH:$JAVA_HOME/bin\"" >> $HOME/.profile
. $HOME/.profile

