[Windows]
api = [ "https://update.code.visualstudio.com/api/update/win32-x64/stable/VERSION", "url" ]
url = "https://aka.ms/win32-x64-user-stable"
[macOS]
api = "https://update.code.visualstudio.com/api/update/darwin/stable/VERSION"
[Linux]
api = "https://update.code.visualstudio.com/api/update/linux-snap-x64/stable/VERSION"